services:
  
  server:
    image: docker.io/drone/drone:2
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Paris
      - DRONE_LOGS_DEBUG=true
      - DRONE_SERVER_HOST=drone.orion-beauny-sugot.com
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET=
      - DRONE_GITHUB_CLIENT_ID=
      - DRONE_GITHUB_CLIENT_SECRET=
    volumes:
      - ./data:/var/lib/drone

  agent:
    image: docker.io/drone/drone-runner-docker:1
    restart: always
    depends_on:
      - server
    ports:
      - 3000:3000
    environment:
      - Europe/Paris
      - DRONE_RPC_HOST=server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock